const foodDatabase = [
  // Frutas
  {
    id: 'f1',
    name: 'Manzana',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    category: 'Frutas',
  },
  {
    id: 'f2',
    name: 'Plátano',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    category: 'Frutas',
  },
  {
    id: 'f3',
    name: 'Naranja',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    category: 'Frutas',
  },
  {
    id: 'f4',
    name: 'Fresa',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    category: 'Frutas',
  },
  {
    id: 'f5',
    name: 'Piña',
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    category: 'Frutas',
  },

  // Verduras
  {
    id: 'v1',
    name: 'Lechuga',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    category: 'Verduras',
  },
  {
    id: 'v2',
    name: 'Espinacas',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    category: 'Verduras',
  },
  {
    id: 'v3',
    name: 'Zanahoria',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    category: 'Verduras',
  },
  {
    id: 'v4',
    name: 'Tomate',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    category: 'Verduras',
  },
  {
    id: 'v5',
    name: 'Brócoli',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    category: 'Verduras',
  },

  // Cereales
  {
    id: 'c1',
    name: 'Arroz blanco',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    category: 'Cereales',
  },
  {
    id: 'c2',
    name: 'Arroz integral',
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    category: 'Cereales',
  },
  {
    id: 'c3',
    name: 'Pan integral',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    category: 'Cereales',
  },
  {
    id: 'c4',
    name: 'Avena',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    category: 'Cereales',
  },
  {
    id: 'c5',
    name: 'Quinoa',
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    category: 'Cereales',
  },
  {
    id: 'c11',
    name: 'Birote/Bolillo',
    calories: 270,
    protein: 8,
    carbs: 50,
    fat: 1,
    category: 'Cereales',
  },
  {
    id: 'c12',
    name: 'Tortilla de maíz',
    calories: 64,
    protein: 1.9,
    carbs: 13.8,
    fat: 0.3,
    category: 'Cereales',
  },
  {
    id: 'c13',
    name: 'Tortilla de harina',
    calories: 159,
    protein: 4.5,
    carbs: 25.6,
    fat: 4.2,
    category: 'Cereales',
  },
  {
    id: 'c14',
    name: 'Tostadas horneadas (salmas)',
    calories: 120,
    protein: 2,
    carbs: 20,
    fat: 3,
    category: 'Cereales',
  },
  {
    id: 'c15',
    name: 'Pan de caja que no sea integral',
    calories: 265,
    protein: 7.5,
    carbs: 49,
    fat: 3.2,
    category: 'Cereales',
  },
  {
    id: 'c16',
    name: 'Tostada frita',
    calories: 150,
    protein: 2,
    carbs: 18,
    fat: 8,
    category: 'Cereales',
  },
  {
    id: 'c17',
    name: 'Galletas maría',
    calories: 430,
    protein: 6.7,
    carbs: 76,
    fat: 10,
    category: 'Cereales',
  },
  {
    id: 'c18',
    name: 'Galleta tipo Chokys',
    calories: 502,
    protein: 5.5,
    carbs: 64,
    fat: 24,
    category: 'Cereales',
  },
  {
    id: 'c19',
    name: 'Pan dulce',
    calories: 297,
    protein: 6,
    carbs: 50,
    fat: 8,
    category: 'Cereales',
  },
  {
    id: 'c20',
    name: 'Papa',
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    category: 'Cereales',
  },

  // Legumbres
  {
    id: 'l1',
    name: 'Lentejas',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    category: 'Legumbres',
  },
  {
    id: 'l2',
    name: 'Garbanzos',
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    category: 'Legumbres',
  },
  {
    id: 'l3',
    name: 'Frijoles negros',
    calories: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    category: 'Legumbres',
  },
  {
    id: 'lg1',
    name: 'Frijoles de la olla',
    calories: 347,
    protein: 22,
    carbs: 63,
    fat: 1.2,
    category: 'Legumbres',
  },
  {
    id: 'lg2',
    name: 'Frijoles refritos',
    calories: 217,
    protein: 13,
    carbs: 39,
    fat: 1.3,
    category: 'Legumbres',
  },
  {
    id: 'lg4',
    name: 'Bebida vegetal de soya',
    calories: 54,
    protein: 3.3,
    carbs: 4,
    fat: 1.8,
    category: 'Legumbres',
  },

  // Carnes y Pescados
  {
    id: 'cp1',
    name: 'Pollo (pechuga)',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    category: 'Carnes y Pescados',
  },
  {
    id: 'cp2',
    name: 'Ternera',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 17,
    category: 'Carnes y Pescados',
  },
  {
    id: 'cp3',
    name: 'Salmón',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    category: 'Carnes y Pescados',
  },
  {
    id: 'cp4',
    name: 'Huevos',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    category: 'Carnes y Pescados',
  },

  // Derivados animales
  {
    id: 'da1',
    name: 'Chorizo',
    calories: 455,
    protein: 25,
    carbs: 1.7,
    fat: 38,
    category: 'Derivados animales',
  },
  {
    id: 'da2',
    name: 'Tocino',
    calories: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    category: 'Derivados animales',
  },
  {
    id: 'da3',
    name: 'Pechuga de pavo',
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    category: 'Derivados animales',
  },
  {
    id: 'da4',
    name: 'Jamón',
    calories: 145,
    protein: 20,
    carbs: 1.5,
    fat: 6,
    category: 'Derivados animales',
  },
  {
    id: 'da5',
    name: 'Salchicha',
    calories: 300,
    protein: 12,
    carbs: 2,
    fat: 27,
    category: 'Derivados animales',
  },
  {
    id: 'da6',
    name: 'Chicharrón',
    calories: 544,
    protein: 61,
    carbs: 0,
    fat: 31,
    category: 'Derivados animales',
  },
  {
    id: 'da7',
    name: 'Bistec de res',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 17,
    category: 'Derivados animales',
  },
  {
    id: 'da8',
    name: 'Pollo frito',
    calories: 246,
    protein: 28,
    carbs: 8,
    fat: 12,
    category: 'Derivados animales',
  },
  {
    id: 'da9',
    name: 'Filete de pescado o atún a la plancha',
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 12,
    category: 'Derivados animales',
  },
  {
    id: 'da10',
    name: 'Atún en lata',
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    category: 'Derivados animales',
  },
  {
    id: 'da11',
    name: 'Chuleta de cerdo',
    calories: 231,
    protein: 25,
    carbs: 0,
    fat: 15,
    category: 'Derivados animales',
  },

  // Lácteos
  {
    id: 'd1',
    name: 'Leche entera',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    category: 'Lácteos',
  },
  {
    id: 'd2',
    name: 'Yogur natural',
    calories: 59,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    category: 'Lácteos',
  },
  {
    id: 'd3',
    name: 'Queso fresco',
    calories: 98,
    protein: 14,
    carbs: 3.3,
    fat: 4.3,
    category: 'Lácteos',
  },
  {
    id: 'lt1',
    name: 'Leche descremada',
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    category: 'Lácteos',
  },
  {
    id: 'lt2',
    name: 'Leche deslactosada',
    calories: 52,
    protein: 3.3,
    carbs: 5,
    fat: 2.4,
    category: 'Lácteos',
  },
  {
    id: 'lt3',
    name: 'Queso panela',
    calories: 98,
    protein: 14,
    carbs: 3.3,
    fat: 4.3,
    category: 'Lácteos',
  },
  {
    id: 'lt4',
    name: 'Queso para fundir (manchego, asadero o mozzarella)',
    calories: 300,
    protein: 22,
    carbs: 2,
    fat: 22,
    category: 'Lácteos',
  },
  {
    id: 'lt5',
    name: 'Queso oaxaca',
    calories: 356,
    protein: 22,
    carbs: 3,
    fat: 28,
    category: 'Lácteos',
  },
  {
    id: 'lt6',
    name: 'Requesón o cottage',
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    category: 'Lácteos',
  },

  // Frutos Secos y Semillas
  {
    id: 'ns1',
    name: 'Almendras',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    category: 'Frutos Secos y Semillas',
  },
  {
    id: 'ns2',
    name: 'Nueces',
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    category: 'Frutos Secos y Semillas',
  },
  {
    id: 'ns3',
    name: 'Semillas de chía',
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    category: 'Frutos Secos y Semillas',
  },
  {
    id: 'gr1',
    name: 'Cacahuate',
    calories: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    category: 'Frutos Secos y Semillas',
  },
  {
    id: 'gr2',
    name: 'Nuez de la india',
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    category: 'Frutos Secos y Semillas',
  },

  // Aceites y Grasas
  {
    id: 'ag1',
    name: 'Aceite de oliva',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    category: 'Aceites y Grasas',
  },
  {
    id: 'ag2',
    name: 'Aguacate',
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    category: 'Aceites y Grasas',
  },
  {
    id: 'gr3',
    name: 'Crema de cacahuate',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    category: 'Aceites y Grasas',
  },
  {
    id: 'gr4',
    name: 'Mantequilla',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    category: 'Aceites y Grasas',
  },
  {
    id: 'gr5',
    name: 'Bebida vegetal de almendras',
    calories: 13,
    protein: 0.5,
    carbs: 1,
    fat: 1.1,
    category: 'Aceites y Grasas',
  },

  // Otros
  {
    id: 'o1',
    name: 'Tofu',
    calories: 144,
    protein: 17,
    carbs: 3,
    fat: 8,
    category: 'Otros',
  },
  {
    id: 'o2',
    name: 'Tempeh',
    calories: 193,
    protein: 20,
    carbs: 9,
    fat: 11,
    category: 'Otros',
  },
];

export default foodDatabase;
